language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
sudo: false
#install: npm install
script: npm run test
#after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"